[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://drive.google.com"
    Content-Security-Policy = "frame-src https://drive.google.com;"